[[LCIO_Julia_Wrapper]]
arch = "x86_64"
git-tree-sha1 = "37cfccc43d2d3637633e0ce197e28f5f873abb57"
libc = "glibc"
os = "linux"

    [[LCIO_Julia_Wrapper.download]]
    sha256 = "524e621604318612d9214b2c66825af2e398bc67f15b473bce0e1d354dc0dda4"
    url = "https://github.com/jstrube/LCIO_Julia_Wrapper_jll.jl/releases/download/LCIO_Julia_Wrapper-v0.101.0+0/LCIO_Julia_Wrapper.v0.101.0.x86_64-linux-gnu.tar.gz"
