[[LCIO_Julia_Wrapper]]
arch = "x86_64"
git-tree-sha1 = "44f03d53ab90bd4b1b4c2f9c63bbdbe99845afe8"
libc = "glibc"
os = "linux"

    [[LCIO_Julia_Wrapper.download]]
    sha256 = "8099a191e08ad6ba8f46ce6871516bf94e45e1f22c25d21ba9db6cb238d0b839"
    url = "https://github.com/jstrube/LCIO_Julia_Wrapper_jll.jl/releases/download/LCIO_Julia_Wrapper-v0.102.0+0/LCIO_Julia_Wrapper.v0.102.0.x86_64-linux-gnu.tar.gz"
