[[LCIO_Julia_Wrapper]]
arch = "x86_64"
git-tree-sha1 = "4966ca3ec54615e3aaea6fea9e10c3e0d54779d4"
os = "macos"

    [[LCIO_Julia_Wrapper.download]]
    sha256 = "cc9512bd63813ca33619a3c12e795b4feb273f191a1b81eb4eaeb3bb0296c48f"
    url = "https://github.com/jstrube/LCIO_Julia_Wrapper_jll.jl/releases/download/LCIO_Julia_Wrapper-v0.103.0+0/LCIO_Julia_Wrapper.v0.103.0.x86_64-apple-darwin14.tar.gz"
[[LCIO_Julia_Wrapper]]
arch = "x86_64"
git-tree-sha1 = "52cb4ad22db7ca49d88a9ff1a865851e965837f6"
libc = "glibc"
os = "linux"

    [[LCIO_Julia_Wrapper.download]]
    sha256 = "e029d192b6cb6000b2f623c832f1a95a725321f01aaced13461d0d611cbf75ba"
    url = "https://github.com/jstrube/LCIO_Julia_Wrapper_jll.jl/releases/download/LCIO_Julia_Wrapper-v0.9.1-alpha+0/LCIO_Julia_Wrapper.v0.9.1-alpha.x86_64-linux-gnu.tar.gz"
[[LCIO_Julia_Wrapper]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7bafc8840110dcdc42ced14f3ed290c779086eab"
libc = "glibc"
os = "linux"

    [[LCIO_Julia_Wrapper.download]]
    sha256 = "ec09454a46fd179b9683436cf6a7d5a79ad20e93934e752c0a749f68a8a1c888"
    url = "https://github.com/jstrube/LCIO_Julia_Wrapper_jll.jl/releases/download/LCIO_Julia_Wrapper-v0.12.0-alpha6+0/LCIO_Julia_Wrapper.v0.12.0-alpha6.x86_64-linux-gnu-cxx11.tar.gz"
